POST {{host}}
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="File"; filename="ubuntu-reference.pdf"

< Media/ubuntu-reference.pdf
--WebAppBoundary--

> Asserts/Should_be_201_created.js
###

GET {{host}}/{{fileName}}

> Asserts/Should_Be_200_OK_octet.js


####

POST {{host}}
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="File"; filename="soveriegn-individual.png"

< Media/soveriegn-individual.png
--WebAppBoundary--

> Asserts/Should_be_201_created.js
###

GET {{host}}{{fileName}}

> Asserts/Should_Be_200_OK_png.js