POST {{host}}
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
x-pub-key: ec642f38bfef46ab7bcdb5aea1dcdc98ca20cbb4cec7fa1066cafbb5a8b07008

--WebAppBoundary
Content-Disposition: form-data; name="File"; filename="ubuntu-reference.pdf"

< ubuntu-reference.pdf
--WebAppBoundary--

> Asserts/Should_be_201_created.js
###

GET {{host}}/{{fileName}}

####

POST {{host}}
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary
x-pub-key: ec642f38bfef46ab7bcdb5aea1dcdc98ca20cbb4cec7fa1066cafbb5a8b07008

--WebAppBoundary
Content-Disposition: form-data; name="File"; filename="soveriegn-individual.png"

< soveriegn-individual.png
--WebAppBoundary--

> Asserts/Should_be_201_created.js
###

GET {{host}}/{{fileName}}